In [1]:
import numpy as np
import pandas as pd

In [3]:
arr_1 = np.random.rand(20)
arr_1

array([0.23213254, 0.51388624, 0.71394544, 0.52147495, 0.88327044,
       0.08924051, 0.40298256, 0.94115152, 0.33364818, 0.87508976,
       0.55016915, 0.55266919, 0.66705253, 0.28944162, 0.79467828,
       0.97974478, 0.7555812 , 0.63645885, 0.47457467, 0.75376897])

In [4]:
condition_arr_1 = np.where(arr_1 > 0.5, 1, 0)
condition_arr_1

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [5]:
arr_1 * 10

array([2.32132543, 5.13886238, 7.1394544 , 5.21474954, 8.8327044 ,
       0.89240512, 4.02982562, 9.41151521, 3.33648182, 8.75089756,
       5.50169154, 5.52669186, 6.67052528, 2.8944162 , 7.94678283,
       9.79744784, 7.55581199, 6.36458853, 4.74574671, 7.53768968])

In [7]:
mat_1 = np.random.randint(1, 20, 9).reshape(3, 3)
mat_2 = np.random.randint(1, 100, 9).reshape(3, 3)

In [8]:
mat_1

array([[ 9,  9,  1],
       [12, 11, 11],
       [ 5,  9, 10]])

In [9]:
mat_2

array([[44, 27, 53],
       [11, 18, 88],
       [66, 57, 22]])

In [10]:
mat_1 * mat_2

array([[396, 243,  53],
       [132, 198, 968],
       [330, 513, 220]])

In [11]:
mat_1 + mat_2

array([[53, 36, 54],
       [23, 29, 99],
       [71, 66, 32]])

In [13]:
dat_1 = np.linalg.det(mat_1)
print(dat_1)
dat_2 = np.linalg.det(mat_2)
print(dat_2)

-432.99999999999994
-82730.99999999994


In [14]:
eig_1 = np.linalg.eig(mat_1)
print(eig_1)
eig_2 = np.linalg.eig(mat_2)
print(eig_2)

EigResult(eigenvalues=array([26.01619353,  6.53185463, -2.54804815]), eigenvectors=array([[-0.41791009, -0.6937131 ,  0.56491258],
       [-0.73005902,  0.1111739 , -0.76043978],
       [-0.54070785,  0.71161963,  0.32032034]]))
EigResult(eigenvalues=array([130.22532996,  11.08508985, -57.31041981]), eigenvectors=array([[-0.5561313 , -0.65559431, -0.14402677],
       [-0.54590163,  0.75477382, -0.74287354],
       [-0.6266653 ,  0.02264028,  0.65375469]]))


In [15]:
arr_2 = np.random.randint(0, 100, 16).reshape(4, 4)
arr_2

array([[38,  5,  4, 32],
       [25, 69, 53, 35],
       [ 5,  1, 12, 22],
       [79, 73, 17, 18]])

In [16]:
ones_arr_2 = np.ones((4, 4)) + arr_2
ones_arr_2

array([[39.,  6.,  5., 33.],
       [26., 70., 54., 36.],
       [ 6.,  2., 13., 23.],
       [80., 74., 18., 19.]])

In [17]:
arr_2[arr_2 > 50]

array([69, 53, 79, 73])

In [18]:
np.where(arr_2 >50, 50, arr_2)

array([[38,  5,  4, 32],
       [25, 50, 50, 35],
       [ 5,  1, 12, 22],
       [50, 50, 17, 18]])

In [19]:
arr_3 = np.random.randint(0, 10, 9).reshape(3,3)
arr_3

array([[4, 2, 7],
       [1, 2, 0],
       [4, 7, 6]])

In [20]:
arr_4 = np.random.randint(0 , 10, 3)
arr_4

array([9, 1, 1])

In [21]:
arr_3 + arr_4

array([[13,  3,  8],
       [10,  3,  1],
       [13,  8,  7]])