## NumPy

In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [3]:
np.array(list_1)

array([1, 2, 3])

In [4]:
list_2 =[[1,2,3],[4,5,6]]
list_2

[[1, 2, 3], [4, 5, 6]]

In [5]:
np.array(list_2)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(2)

array([0.21270268, 0.62275956])

In [14]:
np.random.rand(2, 2)

array([[0.06673411, 0.86793848],
       [0.41168046, 0.45549314]])

In [15]:
np.random.randint(0, 100)

7

In [17]:
np.random.randint(0, 100, 5)

array([51, 17, 91,  0, 59])

In [18]:
np.math.inf

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_7308\4145642268.py:1: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  np.math.inf


inf

In [19]:
np.math.nan

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_7308\1013997921.py:1: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  np.math.nan


nan

In [21]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [31]:
arr.shape

(5,)

In [35]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [39]:
arr2 = np.random.randint(0, 100, 25)
arr2

array([91, 74, 61, 60, 93, 48, 69,  1,  5, 92, 28,  0, 83, 86, 14, 71, 40,
       43, 94, 89, 82, 83, 77, 11, 62])

In [40]:
arr2.shape

(25,)

In [41]:
arr2.reshape(5,5)

array([[91, 74, 61, 60, 93],
       [48, 69,  1,  5, 92],
       [28,  0, 83, 86, 14],
       [71, 40, 43, 94, 89],
       [82, 83, 77, 11, 62]])

In [43]:
arr2.max()

94

In [44]:
arr2.min()

0

In [45]:
arr2.flatten()

array([91, 74, 61, 60, 93, 48, 69,  1,  5, 92, 28,  0, 83, 86, 14, 71, 40,
       43, 94, 89, 82, 83, 77, 11, 62])

## vstack hstack concantenate

In [46]:
day1= np.array([[1,2],[3,4]])
day2= np.array([[11,2],[6,5]])
np.vstack((day1, day2))

array([[ 1,  2,  3,  4],
       [11,  2,  6,  5]])

In [47]:
np.hstack((day1, day2))

array([ 1,  2,  3,  4, 11,  2,  6,  5])

In [53]:
np.concatenate((day1, day2), axis=0)

array([ 1,  2,  3,  4, 11,  2,  6,  5])

In [63]:
day1= np.array([[1,2],[3,4]])
day2= np.array([[11,2],[6,5]])
np.concatenate((day1, day2), axis=1)

array([[ 1,  2, 11,  2],
       [ 3,  4,  6,  5]])

In [65]:
day1.dtype

dtype('int32')

## indexing

In [66]:
day1

array([[1, 2],
       [3, 4]])

In [67]:
for i in day1:
    print(i)

[1 2]
[3 4]


In [68]:
day1[0]

array([1, 2])

In [69]:
day1[1]

array([3, 4])

In [74]:
update_index = np.arange(0,100,3)
update_index

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [75]:
update_index[0:9] = 1
update_index

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## copy

In [77]:
update_index = np.arange(0,100,3)
update_index

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [78]:
update_with_copy= update_index.copy()[0:6]
update_with_copy

array([ 0,  3,  6,  9, 12, 15])

In [79]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [81]:
matrix_triu = np.random.randint(0,100,25).reshape(5, 5)
matrix_triu

array([[49, 54, 58, 36,  0],
       [90, 87, 40,  7,  1],
       [77, 42, 39, 93, 93],
       [30, 95, 34, 37, 92],
       [ 7, 54, 54, 94, 51]])

In [82]:
np.triu(matrix_triu)

array([[49, 54, 58, 36,  0],
       [ 0, 87, 40,  7,  1],
       [ 0,  0, 39, 93, 93],
       [ 0,  0,  0, 37, 92],
       [ 0,  0,  0,  0, 51]])

In [84]:
np.tril(matrix_triu)

array([[49,  0,  0,  0,  0],
       [90, 87,  0,  0,  0],
       [77, 42, 39,  0,  0],
       [30, 95, 34, 37,  0],
       [ 7, 54, 54, 94, 51]])

In [85]:
matrix_triu > 50

array([[False,  True,  True, False, False],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True],
       [False,  True, False, False,  True],
       [False,  True,  True,  True,  True]])

In [87]:
np.log(matrix_triu)

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_7308\43242826.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(matrix_triu)


array([[3.8918203 , 3.98898405, 4.06044301, 3.58351894,       -inf],
       [4.49980967, 4.46590812, 3.68887945, 1.94591015, 0.        ],
       [4.34380542, 3.73766962, 3.66356165, 4.53259949, 4.53259949],
       [3.40119738, 4.55387689, 3.52636052, 3.61091791, 4.52178858],
       [1.94591015, 3.98898405, 3.98898405, 4.54329478, 3.93182563]])

In [88]:
np.exp(matrix_triu)

array([[1.90734657e+21, 2.83075330e+23, 1.54553894e+25, 4.31123155e+15,
        1.00000000e+00],
       [1.22040329e+39, 6.07603023e+37, 2.35385267e+17, 1.09663316e+03,
        2.71828183e+00],
       [2.75851345e+33, 1.73927494e+18, 8.65934004e+16, 2.45124554e+40,
        2.45124554e+40],
       [1.06864746e+13, 1.81123908e+41, 5.83461743e+14, 1.17191424e+16,
        9.01762841e+39],
       [1.09663316e+03, 2.83075330e+23, 2.83075330e+23, 6.66317622e+40,
        1.40934908e+22]])

## where

In [89]:
np.where(matrix_triu < 50 , 0 , matrix_triu)

array([[ 0, 54, 58,  0,  0],
       [90, 87,  0,  0,  0],
       [77,  0,  0, 93, 93],
       [ 0, 95,  0,  0, 92],
       [ 0, 54, 54, 94, 51]])