# Pandas

# Different data structures in Pandas

### Series & DataFrame & Index

#### Series

In [38]:
dic_1 = {'Alex': 400, "David": 500, "Sara": 450}
list_1 = ["A", "B", "C", "D"]
pd.Series(list_1)

0    A
1    B
2    C
3    D
dtype: object

In [39]:
import pandas as pd
import numpy as np

In [40]:
pd.Series([400,500,450],["Alex","David","Sara"])

Alex     400
David    500
Sara     450
dtype: int64

In [41]:
sr = pd.Series([400,500,450],["Alex","David","Sara"])

In [42]:
sr["David"]

500

In [43]:
sr[2]

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_6576\2096876498.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[2]


450

### using Dic

In [44]:
sr_2 = pd.Series(dic_1)
sr_2

Alex     400
David    500
Sara     450
dtype: int64

### using array

In [45]:
arr_1 = np.array([1,2,3,4,5])

In [46]:
sr_3 = pd.Series(arr_1)
sr_3

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [47]:
dic_1 = pd.Series([400,500,450],["Alex","David","Sara"])
dic_2 = pd.Series([600,800,250],["David","Alex","Sara"])

sum_value = dic_1 + dic_2
sum_value

Alex     1200
David    1100
Sara      700
dtype: int64

In [48]:
sum_value = dic_1 * dic_2
sum_value

Alex     320000
David    300000
Sara     112500
dtype: int64

In [49]:
sum_value = dic_1 - dic_2
sum_value

Alex    -400
David   -100
Sara     200
dtype: int64

In [50]:
sum_value = dic_1 / dic_2
sum_value

Alex     0.500000
David    0.833333
Sara     1.800000
dtype: float64

In [51]:
dic_3 = pd.Series([400,500,450,100],["Alex","David","Sara", "Ali"])
dic_4 = pd.Series([600,800,250, 40],["David","Alex","Sara", "Samira"])
sum_value_nan = dic_3 + dic_4
sum_value_nan

Alex      1200.0
Ali          NaN
David     1100.0
Samira       NaN
Sara       700.0
dtype: float64

#### DataFrame

In [52]:
df = np.random.randint(0, 100, 25).reshape(5, 5)
print(df)
data_frame = pd.DataFrame(df, ["a", "b", "c", "d", "e"], ["A", "B", "C", "D", "E"])
print(data_frame)

[[65 17 77 17 12]
 [56 55 22 71  8]
 [45  7 84 62  1]
 [12 81 44 79 29]
 [24 23 63 80 82]]
    A   B   C   D   E
a  65  17  77  17  12
b  56  55  22  71   8
c  45   7  84  62   1
d  12  81  44  79  29
e  24  23  63  80  82


In [53]:
data_frame["A"]

a    65
b    56
c    45
d    12
e    24
Name: A, dtype: int32

In [54]:
data_frame[["A", "D"]]

A   D
a  65  17
b  56  71
c  45  62
d  12  79
e  24  80

## loc & iloc

In [55]:
data_frame.loc["a"]

A    65
B    17
C    77
D    17
E    12
Name: a, dtype: int32

In [56]:
data_frame.iloc[1]

A    56
B    55
C    22
D    71
E     8
Name: b, dtype: int32

## creating new column

In [58]:
per = pd.DataFrame([[400,500,450,100], [500, 600, 430, 900],[200, 300, 120, 780], [210, 880, 640, 90]], ["Baran","Sahar","Kamiar", "Habib"], ["Mehre","Aban","Azar", "Dey"])
print(per)

        Mehre  Aban  Azar  Dey
Baran     400   500   450  100
Sahar     500   600   430  900
Kamiar    200   300   120  780
Habib     210   880   640   90


In [59]:
per["Bahman"]= [100, 200, 300, 400]
per

Mehre  Aban  Azar  Dey  Bahman
Baran     400   500   450  100     100
Sahar     500   600   430  900     200
Kamiar    200   300   120  780     300
Habib     210   880   640   90     400

## drop

In [60]:
per

Mehre  Aban  Azar  Dey  Bahman
Baran     400   500   450  100     100
Sahar     500   600   430  900     200
Kamiar    200   300   120  780     300
Habib     210   880   640   90     400

In [61]:
per.drop("Mehre", axis = 1)

Aban  Azar  Dey  Bahman
Baran    500   450  100     100
Sahar    600   430  900     200
Kamiar   300   120  780     300
Habib    880   640   90     400

In [62]:
per.drop("Baran", axis = 0)

Mehre  Aban  Azar  Dey  Bahman
Sahar     500   600   430  900     200
Kamiar    200   300   120  780     300
Habib     210   880   640   90     400

In [65]:
df_1402 = pd.Series([67 , 1999 , 299, 300,123, 34 ,12] , ["Iran" , "Japan" , "usa" , "turk" , "France", "Arbic" , " Afghanestan"])
df_1402

Iran              67
Japan           1999
usa              299
turk             300
France           123
Arbic             34
 Afghanestan      12
dtype: int64

In [66]:
born = pd.Series([0.5 , 2 ,3 , 4 ,0.9, 0.2 ,0.1] , ["Iran" , "Japan" , "usa" , "turk" , "France", "Arbic" , " Afghanestan"])
born

Iran            0.5
Japan           2.0
usa             3.0
turk            4.0
France          0.9
Arbic           0.2
 Afghanestan    0.1
dtype: float64

In [67]:
df_1403 = born + df_1402
df_1403

Iran              67.5
Japan           2001.0
usa              302.0
turk             304.0
France           123.9
Arbic             34.2
 Afghanestan      12.1
dtype: float64

In [68]:
death = pd.Series([0.2 , 1.5 ,5  , 2 ,1.5, 0.5 ,2] , ["Iran" , "Japan" , "usa" , "turk" , "France", "Arbic" , " Afghanestan"])
df_1402 / 2

Iran             33.5
Japan           999.5
usa             149.5
turk            150.0
France           61.5
Arbic            17.0
 Afghanestan      6.0
dtype: float64